owasp-top10-2017-apps/a4/vinijr-blog/deployments/Dockerfile
owasp-top10-2017-apps/a4/vinijr-blog/deployments/docker-compose.yml

Mount folder as volume, instead to add as image content, to avoid re-run container (`make install`)  to add new changes to Apache server.

[A4] Mount app folder as docker volume.

---

owasp-top10-2017-apps/a7/fofocando/app/routes.py
owasp-top10-2017-apps/a7/fofocando/deployments/Dockerfile
owasp-top10-2017-apps/a7/fofocando/deployments/docker-compose.yml

Mount folder as volume, instead to add as image content, to avoid re-run container (make install) to add new changes to server.

[A7] Mount app folder as docker volume.

---

owasp-top10-2017-apps/a7/fofocando/deployments/Dockerfile

Pull request #30 changes how the container is built and executed. 
But `requirements.txt` was missing while building the image.

[A7] Fix Dockerfile

---

owasp-top10-2017-apps/a8/amarelo-designs/deployments/Dockerfile
owasp-top10-2017-apps/a8/amarelo-designs/deployments/docker-compose.yml

Mount folder as volume, instead to add as image content, to avoid re-run container (make install) to add new changes to server.
Also install `netcat` to docker image for attack narrative works.

[A8] Mount app folder as docker volume.

---

owasp-top10-2017-apps/a10/games-irados/app/routes.py
owasp-top10-2017-apps/a10/games-irados/deployments/Dockerfile
owasp-top10-2017-apps/a10/games-irados/deployments/docker-compose.yml

Mount folder as volume, instead to add as image content, to avoid re-run container (make install) to add new changes to server.

[A10] Mount app folder as docker volume.

---

owasp-top10-2017-apps/a10/games-irados/app/model/db.py

The application flow, uses the second return parameter to represent `success` or `fail`, but when the application try to retrieve the `user_password` and it is empty, the `success` parameter continues to be `True` even if this value is empty.
This pull request suggest to return `False` if this value doesn't exists.

[A10] Return success message True only if the user_password is not empty

---

owasp-top10-2017-apps/a2/saidajaula-monster/app/app.py
owasp-top10-2017-apps/a2/saidajaula-monster/deployments/Dockerfile
owasp-top10-2017-apps/a2/saidajaula-monster/deployments/docker-compose.yml

Mount folder as volume, instead to add as image content, to avoid re-run container (make install) to add new changes to server.

[A2] Mount app folder as docker volume.

---

owasp-top10-2017-apps/a4/vinijr-blog/README.md

Link to `contact.php` file was broken.

[DOCS] Fix broken link in A4 README

---

owasp-top10-2017-apps/a6/misconfig-wordpress/README.md
owasp-top10-2017-apps/a6/stegonography/README.md
owasp-top10-2017-apps/a9/cimentech/README.md

This PR adds a warning to the README of three web apps about the installation of ExploitDB.
```sh
⚠️ 'The next command will install several exploit codes in your system and many of them may trigger antiviruses alerts'
brew install exploitdb
```

Include a warning before the instruction to install ExploitDB

---

docs/README_Template.md

This PR aims to fix a broken path to an image in the README template.
* `docs/README_Template.md`: Fix broken image path.

Fix broken image in the README template

---

owasp-top10-2017-apps/a5/ecommerce-api/app/scripts/generate-passwords.sh

This PR fixes a problem when users start ecommerce-api.
```
mac301188:ecommerce-api manoel.junior$ make install
ERROR: In file ./.env: environment variable name 'export MONGO_DATABASE_USERNAME' may not contains whitespace.
make: *** [compose] Error 1
```
This problem occurs because generated `.env` file needs have only environment variables names and values, and not need `export` command.

[FIX] Remove export from .env file

---

owasp-top10-2017-apps/a9/cimentech/app/html/modules/dashboard/dashboard.css

Unit of measure 'px' is redundant with zero values and properties may be safely replaced with 'background' shorthand

Upgrade in CSS standard

---

owasp-top10-2017-apps/a2/saidajaula-monster/Makefile
owasp-top10-2017-apps/a2/saidajaula-monster/deployments/exploit.sh

The goal of this PR is to add an easy way to verify if the app can still be exploited by the commands shown in it's [attack narrative](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2017-apps/a2/saidajaula-monster#attack-narrative).
* `owasp-top10-2017-apps/a2/saidajaula-monster/Makefile`: Add `make exploit` command to call the exploit script.
* `owasp-top10-2017-apps/a2/saidajaula-monster/deployments/exploit.sh`: Adds commands to try and exploit the app the same way as shown in the attack narrative.
With the app running, simply run the `make exploit` command:
If the app is no longer exploitable through the commands shown in the attack narrative:

Add script to verify if Saidajaula Monster is still exploitable

---

owasp-top10-2016-mobile/m2/cool_games/mobile/ios/Flutter/Debug.xcconfig
owasp-top10-2016-mobile/m2/cool_games/mobile/ios/Flutter/Release.xcconfig
owasp-top10-2016-mobile/m2/cool_games/mobile/ios/Podfile
owasp-top10-2016-mobile/m2/cool_games/mobile/ios/Podfile.lock
owasp-top10-2016-mobile/m2/cool_games/mobile/ios/Runner.xcodeproj/project.pbxproj
owasp-top10-2016-mobile/m2/cool_games/mobile/ios/Runner.xcworkspace/contents.xcworkspacedata
owasp-top10-2016-mobile/m2/cool_games/mobile/lib/views/auth_screen.dart
owasp-top10-2016-mobile/m2/cool_games/mobile/lib/views/register_screen.dart

Different platforms have different network configurations regarding to the host machine:
- On the Android device emulator managed by AVD, [the host machine is reached using the 10.0.2.2 address](https://developer.android.com/studio/run/emulator-networking)
- On the iOS device simulator (Simulator.app, bundled with xcode), [the host machine is accessible using localhost](https://stackoverflow.com/a/6077929)
Having a hardcoded URL for the backend is an issue.
The app now selects the backend host based on the platform. This PR also includes files generated and updated by the xcode build.
The app should work in both emulators:
- [Android](https://flutter.dev/docs/get-started/install/macos#android-setup)
- [iOS](https://flutter.dev/docs/get-started/install/macos#ios-setup)

Add conditional for backend host

---

.github/PULL_REQUEST_TEMPLATE/mitigation-solution.md
.github/pull_request_template.md

We've had for quite a while a Pull Request template that wasn't really working where it was. The goal of this PR is to set the path and the file name right so every new PR will use it.
* `.github/PULL_REQUEST_TEMPLATE/mitigation-solution.md`: Removed old PR template.
* `.github/pull_request_template.md` : Adds new PR template.

Fix Pull Request template

---

owasp-top10-2017-apps/a9/cimentech/deployments/docker-compose.yml

The application doesn't execute and it is giving the error below:
```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
connections without a password. This is *not* recommended.
```
This error is caused due a changed in the docker-library/postgres ([#589](https://github.com/docker-library/postgres/issues/580)).
It was added the environment variable POSTGRES_PASSWORD in the docker-compose file to fix the error. The value of the password variable must be the same one in the `app/html/sites/default/settings.php` file.
The install command should work properly: 
```
make …
```

Add the environment variable POSTGRES_PASSWORD

---

owasp-top10-2017-apps/a2/saidajaula-monster/app/model/password.py
owasp-top10-2017-apps/a2/saidajaula-monster/deployments/Dockerfile

Hey There!
Opening this PR to migrate the app Saidajaula Monster Fit - A2 to python3.
Many of the fixes to this app will require libraries that do not support python2 anymore.
Only changed the Dockerfile, and had to update the hashing function on password.py (Appears to be a change in how the pbkdf2_hmac function works, no longer accepts strings but only bytes to hash)

Migrate A2 - Saidajaula Monster Fit app to python3

---

owasp-top10-2021-apps/a6/cimentech/deployments/docker-compose.yml

Using `postgres:latest` was breaking the build, since we are using a deprecated version of `drupal`

Pin Postgres version for a6-cimentech

---

docs/Makefile
owasp-top10-2016-mobile/m2/cool_games/server/Makefile
owasp-top10-2016-mobile/m4/note-box/server/Makefile
owasp-top10-2016-mobile/m5/panda_zap/server/Makefile
owasp-top10-2021-apps/a1/camplake-api/Makefile
owasp-top10-2021-apps/a1/ecommerce-api/Makefile
owasp-top10-2021-apps/a1/tictactoe/Makefile
owasp-top10-2021-apps/a2/snake-pro/Makefile
owasp-top10-2021-apps/a3/comment-killer/Makefile
owasp-top10-2021-apps/a3/copy-n-paste/Makefile
owasp-top10-2021-apps/a3/gossip-world/Makefile
owasp-top10-2021-apps/a3/mongection/Makefile
owasp-top10-2021-apps/a3/sstype/Makefile
owasp-top10-2021-apps/a3/streaming/Makefile
owasp-top10-2021-apps/a5/misconfig-wordpress/Makefile
owasp-top10-2021-apps/a5/stegonography/Makefile
owasp-top10-2021-apps/a5/vinijr-blog/Makefile
owasp-top10-2021-apps/a6/cimentech/Makefile
owasp-top10-2021-apps/a6/golden-hat/Makefile
owasp-top10-2021-apps/a7/insecure-go-project/Makefile
owasp-top10-2021-apps/a7/saidajaula-monster/Makefile
owasp-top10-2021-apps/a8/amarelo-designs/Makefile
owasp-top10-2021-apps/a9/games-irados/Makefile

Create a script in `Makefile` to help users take down your applications.
Now you can install your application and remove it before usage:
```bash
$ make install
SecDevLabs: 👀  Your app is starting!
SecDevLabs: 👀  Your app is still starting... (----*---)
SecDevLabs: 🔥  AX - XX is now running at http://localhost:X
...
$ make compose-down
```

feat: create make compose-down script

---

owasp-top10-2016-mobile/m2/cool_games/server/Makefile
owasp-top10-2016-mobile/m4/note-box/server/Makefile
owasp-top10-2016-mobile/m5/panda_zap/server/Makefile
owasp-top10-2021-apps/a1/camplake-api/Makefile
owasp-top10-2021-apps/a1/ecommerce-api/Makefile
owasp-top10-2021-apps/a1/ecommerce-api/deployments/docker-compose.yml
owasp-top10-2021-apps/a1/tictactoe/Makefile
owasp-top10-2021-apps/a2/snake-pro/Makefile
owasp-top10-2021-apps/a3/comment-killer/Makefile
owasp-top10-2021-apps/a3/copy-n-paste/Makefile
owasp-top10-2021-apps/a3/gossip-world/Makefile
owasp-top10-2021-apps/a3/mongection/Makefile
owasp-top10-2021-apps/a3/sstype/Makefile
owasp-top10-2021-apps/a3/streaming/Makefile
owasp-top10-2021-apps/a5/misconfig-wordpress/Makefile
owasp-top10-2021-apps/a5/stegonography/Makefile
owasp-top10-2021-apps/a5/vinijr-blog/Makefile
owasp-top10-2021-apps/a6/cimentech/Makefile
owasp-top10-2021-apps/a6/golden-hat/Makefile
owasp-top10-2021-apps/a7/insecure-go-project/Makefile
owasp-top10-2021-apps/a7/saidajaula-monster/Makefile
owasp-top10-2021-apps/a8/amarelo-designs/Makefile
owasp-top10-2021-apps/a9/games-irados/Makefile

Add `-p secDevLabs`to `docker-compose`commands to limit scope and not conflict with no related local containers.
Now you can `make install` without worrying about affecting other projects.
#561

feat: add project name to limit compose scope
