owasp-top10-2017-apps/a2/saidajaula-monster/README.md, owasp-top10-2017-apps/a3/insecure-go-project/README.md, owasp-top10-2017-apps/a5/ecommerce-api/README.md, owasp-top10-2017-apps/a6/misconfig-wordpress/README.md, owasp-top10-2017-apps/a8/amarelo-designs/README.md, owasp-top10-2017-apps/a9/cimentech/README.md
=> [DOCS] Update README files

owasp-top10-2017-apps/a1/copy-n-paste/Makefile, owasp-top10-2017-apps/a10/games-irados/Makefile, owasp-top10-2017-apps/a2/saidajaula-monster/Makefile, owasp-top10-2017-apps/a3/insecure-go-project/Makefile, owasp-top10-2017-apps/a4/vinijr-blog/Makefile, owasp-top10-2017-apps/a5/ecommerce-api/Makefile, owasp-top10-2017-apps/a6/misconfig-wordpress/Makefile, owasp-top10-2017-apps/a7/gossip-world/Makefile, owasp-top10-2017-apps/a8/amarelo-designs/Makefile, owasp-top10-2017-apps/a9/cimentech/Makefile
* Added messages after docker compose is executed.
* Added a `sleep` so it waits app and it's dependencies sync properly.
* Added `--remove-orhans` in each `docker-compose` command to turn the process of building secDevLabs apps smoother.
=> [FEAT] Add new messages and remove-orphans into all Makefiles

owasp-top10-2017-apps/a7/gossip-world/app/templates/gossip.html, owasp-top10-2017-apps/a7/gossip-world/app/templates/gossips.html, owasp-top10-2017-apps/a7/gossip-world/app/templates/newgossip.html
Reverts globocom/secDevLabs#100
=> Revert "[Mitigation][A7] Remove safe filter so strings will be escaped"

owasp-top10-2017-apps/a9/cimentech/docs/ATTACK.md
This commit aims to fix a small typo mistake in A9 Attack narrative.
=> [DOCS] Fix typo mistake

owasp-top10-2017-apps/a3/snake-pro/app/views/game.html
=> [FEAT] Change game difficulty

README.md, owasp-top10-2017-apps/a1/copy-n-paste/README.md, owasp-top10-2017-apps/a10/games-irados/README.md, owasp-top10-2017-apps/a2/insecure-go-project/README.md, owasp-top10-2017-apps/a2/saidajaula-monster/README.md, owasp-top10-2017-apps/a3/snake-pro/README.md, owasp-top10-2017-apps/a4/vinijr-blog/README.md, owasp-top10-2017-apps/a5/ecommerce-api/README.md, owasp-top10-2017-apps/a6/misconfig-wordpress/README.md, owasp-top10-2017-apps/a7/gossip-world/README.md, owasp-top10-2017-apps/a8/amarelo-designs/README.md, owasp-top10-2017-apps/a9/cimentech/README.md
=> [DOCS] Adjust labels and mitigation solution links

owasp-top10-2017-apps/a3/snake-pro/app/api/routes.go, owasp-top10-2017-apps/a3/snake-pro/app/main.go
=> [FEAT] Redirect / to /login

README.md
This PR aims to update the main README file with the new A6 app, Stegonography.
=> Update README with new A6 app

owasp-top10-2017-apps/a2/saidajaula-monster/app/app.py
Add message "Logged in!" after a user logs in.
=> [FEAT] Add verbose response to successful login route

owasp-top10-2017-apps/a3/snake-pro/README.md
- Fix indicated file (data is contained in `config.yml` instead of `docker-compose.yml`);
- Add address and port information for connecting to Robo3T in README.
=> [DOCS] Update A3 README

README.md, owasp-top10-2017-apps/a1/copy-n-paste/README.md, owasp-top10-2017-apps/a10/games-irados/README.md, owasp-top10-2017-apps/a2/insecure-go-project/README.md, owasp-top10-2017-apps/a2/saidajaula-monster/README.md, owasp-top10-2017-apps/a3/snake-pro/README.md, owasp-top10-2017-apps/a4/vinijr-blog/README.md, owasp-top10-2017-apps/a5/ecommerce-api/README.md, owasp-top10-2017-apps/a6/misconfig-wordpress/README.md, owasp-top10-2017-apps/a6/stegonography/README.md, owasp-top10-2017-apps/a7/gossip-world/README.md, owasp-top10-2017-apps/a8/amarelo-designs/README.md, owasp-top10-2017-apps/a9/cimentech/README.md
This PR fixes some typos within README files from the web applications
=> Fix English typo within README files

owasp-top10-2017-apps/a5/ecommerce-api/app/db/queries.go, owasp-top10-2017-apps/a5/ecommerce-api/app/handlers/session.go
This PR aims to check if the user provided for registration exists in the database.
=> Check if user exists before registering

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/custom.md
This PR aims to update our issue template by making it appear automatically when opening a new issue.
=> Update issue templates

docs/CONTRIBUTING.md
This PR adds links to Docker Compose Getting Started guide and to Compose File Reference in `CONTRIBUTING.md` file.
=> Add links to docker guides 

.github/PULL_REQUEST_TEMPLATE/mitigation-solution.md
This PR aims to add a template for the mitigation solutions. This way, when someone submits a solution, it will be easier for the secDevLabs community to analyze it.
=> Add mitigation solution PR template

owasp-top10-2017-apps/a1/copy-n-paste/README.md
The example does not work as there is an error with the query
=> [A1] Fix SQL query example

docs/CONTRIBUTING.md
The goal of this PR is to add the project's contribution scope to the `CONTRIBUTING.md` file.
=> Add the project's contribution scope

owasp-top10-2017-apps/a1/mongection/README.md
- Fix db.js link
- Change `findOne` to `find` in login route
=> [DOCS] Update README A1 Mongection

owasp-top10-2017-apps/a7/gossip-world/app/templates/gossip.html, owasp-top10-2017-apps/a7/gossip-world/app/templates/gossips.html, owasp-top10-2017-apps/a7/gossip-world/app/templates/newgossip.html
This PR will replace `#` from home button to the `/gossip` route.
=> Adjust A7 Gossip home links

owasp-top10-2017-apps/a1/copy-n-paste/Makefile, owasp-top10-2017-apps/a1/copy-n-paste/deployments/exploit.sh
This PR will add the `exploit` function in Makefile and some draft to others. If approved, developers will now be able to run the following to check if the app is exploitable or not:
```
$ make exploit
secDevLabs: Exploiting your app locally!
SQL Injection using sleep(10)
User not found or wrong password!
real    0m10.100s
user    0m0.007s
sys     0m0.008s
```
=> Add new functions to Makefile

README.md
This PR aims to add a new row in the available app's matrix with the new M2 - Insecure Data Storage app.
=> Add new M2 app to project's README

README.md
The goal of this PR is to update the project's README to feature our brand new app, [Panda Zap](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2016-mobile/m5/panda_zap).
=> Update README with the new mobile app Panda Zap

owasp-top10-2021-apps/a6/cimentech/README.md
=> Update README.md from [A6] Cimentech

owasp-top10-2016-mobile/m2/cool_games/server/Makefile, owasp-top10-2016-mobile/m4/note-box/server/Makefile, owasp-top10-2016-mobile/m5/panda_zap/server/Makefile, owasp-top10-2021-apps/a1/camplake-api/Makefile, owasp-top10-2021-apps/a1/camplake-api/deployments/mongo-init.js, owasp-top10-2021-apps/a1/ecommerce-api/Makefile, owasp-top10-2021-apps/a1/tictactoe/Makefile, owasp-top10-2021-apps/a2/snake-pro/Makefile, owasp-top10-2021-apps/a3/comment-killer/Makefile, owasp-top10-2021-apps/a3/copy-n-paste/Makefile, owasp-top10-2021-apps/a3/gossip-world/Makefile, owasp-top10-2021-apps/a3/mongection/Makefile, owasp-top10-2021-apps/a3/sstype/Makefile, owasp-top10-2021-apps/a3/streaming/Makefile, owasp-top10-2021-apps/a5/misconfig-wordpress/Makefile, owasp-top10-2021-apps/a5/stegonography/Makefile, owasp-top10-2021-apps/a5/vinijr-blog/Makefile, owasp-top10-2021-apps/a6/cimentech/Makefile, owasp-top10-2021-apps/a6/golden-hat/Makefile, owasp-top10-2021-apps/a7/insecure-go-project/Makefile, owasp-top10-2021-apps/a7/saidajaula-monster/Makefile, owasp-top10-2021-apps/a8/amarelo-designs/Makefile, owasp-top10-2021-apps/a9/games-irados/Makefile
Replacing secDevLabs project name to lower case to fix #571
=> fix: replace secDevLabs to lower case

owasp-top10-2016-mobile/m2/cool_games/README.md, owasp-top10-2016-mobile/m4/note-box/README.md, owasp-top10-2016-mobile/m5/panda_zap/README.md, owasp-top10-2021-apps/a1/camplake-api/README.md, owasp-top10-2021-apps/a5/stegonography/README.md
Some projects had the PR mitigation search links broken.
The apps were:
- camplake API
- stegonography
- note box
- panda zap
=> Fix Broken PR mitigation link
